server:
  port: 9094
spring:
  datasource:
    hikari:
      maximum-pool-size: 100
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      minimum-idle: 5
      validation-timeout: 5000
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zesgkkzbs20syqe78o.mysql.rds.aliyuncs.com/xiaobaibai?prepStmtCacheSize=517&cachePrepStmts=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT
    username: baiminghui
    password: baiminghui123@

  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        event:
          merge:
            entity_copy_observer: allow

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0
        max-wait: -1
    timeout: 12000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true
feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000
error:
  msg: error.properties

newFilePath: C:\Users\lz\Documents\ExportExcel\
templatePath:  C:\Users\lz\Documents\ExportExcel\template\

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    com.huaxin.cloud.iot: debug